### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by JoaoAparicio** [JuliaImGui/ImPlot.jl#2] opened 2020-09-17 19:45 UTC
```julia
julia> versioninfo()
Julia Version 1.5.1
Commit 697e782ab8 (2020-08-25 20:08 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Pentium(R) 3558U @ 1.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, haswell)
Environment:
  JULIA_DIR = /home/me/.julia
  JULIA_EDITOR = vim
```

```
$ julia ~/.julia/packages/ImPlot/1vXdO/demo/example_plots.jl                                    
┌ Error: GLFW ERROR: code API_UNAVAILABLE msg: GLX: No GLXFBConfigs returned
└ @ Main ~/.julia/packages/ImPlot/1vXdO/demo/example_plots.jl:15
┌ Error: GLFW ERROR: code FORMAT_UNAVAILABLE msg: GLX: Failed to find a suitable GLXFBConfig
└ @ Main ~/.julia/packages/ImPlot/1vXdO/demo/example_plots.jl:15

signal (11): Segmentation fault
in expression starting at /home/me/.julia/packages/ImPlot/1vXdO/demo/example_plots.jl:18
glfwSetWindowUserPointer at /home/me/julia/artifacts/a1e91245761ea49ceed2c708a278f8d90a3d88ad/lib/libglfw.so (unknown line)
CreateWindow at /home/me/.julia/packages/GLFW/CBo9c/src/glfw3.jl:502
CreateWindow at /home/me/.julia/packages/GLFW/CBo9c/src/glfw3.jl:499 [inlined]
CreateWindow at /home/me/.julia/packages/GLFW/CBo9c/src/glfw3.jl:499
unknown function (ip: 0x7efe1d2aaad0)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2231 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2398
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1690 [inlined]
do_call at /buildworker/worker/package_linux64/build/src/interpreter.c:117
eval_value at /buildworker/worker/package_linux64/build/src/interpreter.c:206
eval_stmt_value at /buildworker/worker/package_linux64/build/src/interpreter.c:157 [inlined]
eval_body at /buildworker/worker/package_linux64/build/src/interpreter.c:566
jl_interpret_toplevel_thunk at /buildworker/worker/package_linux64/build/src/interpreter.c:660
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:840
jl_parse_eval_all at /buildworker/worker/package_linux64/build/src/ast.c:913
jl_load_rewrite at /buildworker/worker/package_linux64/build/src/toplevel.c:914
include at ./Base.jl:380
include at ./Base.jl:368
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2214 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2398
exec_options at ./client.jl:296
_start at ./client.jl:506
jfptr__start_51675 at /home/me/julia-1.5.1/lib/julia/sys.so (unknown line)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2214 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2398
jl_apply at /buildworker/worker/package_linux64/build/ui/../src/julia.h:1690 [inlined]
true_main at /buildworker/worker/package_linux64/build/ui/repl.c:106
main at /buildworker/worker/package_linux64/build/ui/repl.c:227
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
_start at /home/me/julia-1.5.1/bin/julia (unknown line)
Allocations: 3036973 (Pool: 3036279; Big: 694); GC: 3
Segmentation fault (core dumped)
```

**Comment by wsphillips** [comment] 2020-09-17 23:31
This looks like a GLFW problem. What distro of linux are you using? Are you using and AMD graphics card/mesa driver stack?

**Comment by JoaoAparicio** [comment] 2020-09-18 07:32
Regarding the first question, here's the answer.

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.7 LTS
Release:        16.04
Codename:       xenial
```

I have no idea about the second question. How can I find that out for you?

**Comment by JoaoAparicio** [comment] 2020-09-19 11:28
Regarding the first question, here's the answer.

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.7 LTS
Release:        16.04
Codename:       xenial
```

I have no idea about the second question. How can I find that out for you?

**Comment by wsphillips** [comment] 2021-01-07 20:41
Sorry for the overdue reply: The problem you posted looks like one I've seen with GLFW and open source drivers used with AMD graphics cards. Do you know if your graphics card is AMD? NVIDIA? integrated Intel? The other issue might be that you're using a rather old version of Ubuntu.

In either case, this looks like it's crashing due to an error with window creation in GLFW when it's trying to use your system's OpenGL drivers. (i.e. it's not a problem with CImGui.jl/ImPlot.jl per se.) One thing to try is installing GLFW.jl and then see whether the following works:

```
using GLFW
window = GLFW.CreateWindow(1280, 720, "Test")
```
If that fails, consider raising an issue on the [GLFW.jl GitHub repo](https://github.com/JuliaGL/GLFW.jl/issues).

**Comment by jpsamaroo** [comment] 2021-01-07 20:59
This is https://github.com/JuliaGL/GLFW.jl/issues/194. I never found the solution (and don't know if it still reproduces, since GLFW.jl doesn't work for unrelated reasons on my system).

**Comment by wsphillips** [comment] 2021-01-31 19:22
Closing since this looks like a GLFW issue.

**Closed as completed by wsphillips** 2021-01-31 19:22 UTC
